ajaxComment/config/routes.rb
AjaxComment::Application.routes.draw do
  resources :comments

end

ajaxComment/app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :body, :name
end

ajaxComment/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

ajaxComment/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments = Comment.all
    respond_to do |format|
      format.html # index.html.erb
      format.rss
    end
  end
  
  def create
    @comment = Comment.create!(params[:comment])
    respond_to do |format|
      format.html { redirect_to comments_path }
      format.js 
    end
  end
  
  def destroy
     @comment = Comment.find(params[:id])
     @comment.destroy
     respond_to do |format|
       format.html { redirect_to comments_path }
       format.js 
     end
   end
  
end

ajaxComment/app/helpers/application_helper.rb
module ApplicationHelper
end

ajaxComment/app/helpers/comments_helper.rb
module CommentsHelper
end

ajaxComment/app/views/comments/_comment.html.erb
<%= div_for comment do %>
  <span class="dateandoptions">
    Posted <%=time_ago_in_words(comment.created_at)%> ago<br />
		<%= button_to 'Delete', comment_path(comment), :method => :delete, :class => "destroy", :remote => true  %>
  </span>
	<p><b><%= comment.name %></b> wrote:</p>
	<br />
  <%= content_tag(:p, comment.body, :class => "comment-body") %>
<% end %>

ajaxComment/app/views/comments/create.js.erb
/* Insert a notice between the last comment and the comment form */
$("#comment-notice").html('<div class="flash notice"><%= escape_javascript(flash.delete(:notice)) %></div>');

/* Replace the count of comments */
$("#comments_count").html("<%= pluralize(Comment.count, 'Comment') %>");

/* Add the new comment to the bottom of the comments list */
$("#comments").append("<%= escape_javascript(render(@comment)) %>");

/* Highlight the new comment */
$("#comment_<%= @comment.id %>").effect("highlight", {}, 3000);

/* Reset the comment form */
$("#new_comment")[0].reset();

ajaxComment/app/views/comments/destroy.js.erb
/* Eliminate the comment by fading it out */
$('#comment_<%= @comment.id %>').fadeOut();
/* Replace the count of comments */
$("#comments_count").html("<%= pluralize(Comment.count, 'Comentaries') %>");

ajaxComment/app/views/comments/index.html.erb
<span id="comments_count"><%= pluralize(@comments.count, "Comment") %></span>
<div id="comments">
  <%= render :partial => @comments, :locals => { :list => true } %>
</div>

<hr />

<div id="comment-notice"></div>

<h2>Say something!</h2>
<%= form_for Comment.new, :remote => true do |f| %>
	<%= f.label :name, "Your name" %><br />
	<%= f.text_field :name %><br />
	<%= f.label :body, "Comment" %><br />
	<%= f.text_area :body, :rows => 8 %><br />
	<%= f.submit "Add comment" %>
<% end %>

ajaxComment/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AjaxComment</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%=javascript_include_tag  "http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"%>
  <%=javascript_include_tag  "http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/jquery-ui.min.js"%>
  <%=javascript_include_tag "jquery-rails.js"%>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>